### ISSUE TITLE
Adding current and voltage per string

### ISSUE THREAD

**Issue by sauermouth** [derenback/Domoticz-SMA-Inverter#1]
Hi,

Thanks for your effort so far on this project. It runs perfectly in Domoticz!

Is it possible for you to add the following registers?
30769 - Current of String A in Ampere (example: 3224 = 3,224 ampere)
30771 - Voltage of String A in Volt (example: 59180 = 591,80 volt)
30957 - Current of String B in Ampere 
30959 - Voltage of String B in Volt

I've tested these registers on my SMA TriPower STP 10.0-3AV-40.
This way we can log the current and voltage of the DC-side. Which makes it possible to analyse if the system is running properly.

**Comment by derenback** [comment]
Hi! 
Great suggestion. I have created a pull request for this and will test it as soon as possible.
Will merge this when verified working.
If you want to take a look the pull request is here:
https://github.com/derenback/Domoticz-SMA-Inverter/pull/2

**Comment by sauermouth** [comment]
I verified the workings. See screenshot in the pull request. Thanks :)
