### ISSUE TITLE
Error on restart - Index Error - when altering the Unit 4 kWh

### ISSUE THREAD

**Issue by Csepp** [derenback/Domoticz-SMA-Inverter#23]
Dear Derenback,

When adding a new SMA to Domoticz with our Plugin all goes well (latest version). But on the first restart it stops:

'onStart' failed 'IndexError':'list index out of range'.
Exception tracback:
Line 127 in ....plugin.py' function onStart
'onHeartbeat' failed 'NameError':name 'client' is not defined'

-->>> now I found the reason - I did move the kWH  to another unit nr. then 4 --> as the unit 4 is processed differently it causes this error.  Now I changed the unit Nr. 4 to be the kWH counter. All works. --> my mistake. Just wanted to share it. 

Seppl

**Comment by derenback** [comment]
OK, thanks for the update.
