### ISSUE TITLE
Pi OS 2023.10 install error

### ISSUE THREAD

**Issue by Imwithstupid007** [derenback/Domoticz-SMA-Inverter#24]
Hi,

With the latest release of Pi OS (2023.10) your installation routine gives an error on:
sudo pip3 install -U pymodbus pymodbusTCP

I'm no Linux expert and don't know the reason but Jeff Geerling gave an work around (https://www.jeffgeerling.com/blog/2023/how-solve-error-externally-managed-environment-when-installing-pip3). Which seems to work BTW.

Thank for your great plugin.

**Comment by derenback** [comment]
@Imwithstupid007 Thank you for the information! I tried it bu upgrading a pi to 2023.10 and got the same issue. 
Used the quick way and deleted the blocking message...
sudo rm -rf /usr/lib/python3.11/EXTERNALLY-MANAGED
After this it was ok to install. 

Not sure if it would be possible to solve in a better way with a virtual environment for Domoticz.
