### ISSUE TITLE
Docker question

### ISSUE THREAD

**Issue by daserra23** [derenback/Domoticz-SMA-Inverter#27]
I am a little confused, the commands in the readme for installing with docker appear to be commands to install domoticz itself as a docker image. Do you have a simple docker-compose.yml file I can use to install this ?

**Comment by daserra23** [comment]
> `cd ~/domoticz/plugins/Domoticz-SMA-Inverter/docker
> sudo docker pull domoticz/domoticz
>

**Comment by daserra23** [comment]
OK, please delete this, resolved, just me being dumb.

**Comment by derenback** [comment]
No worries, I see how the instruction can be a bit confusing. Will try to improve it.

**Comment by daserra23** [comment]
Btw, this is a great little plugin, much better than the clunky sbfspot version I used previously.
