### ISSUE TITLE
Debian 12 python/venv solution

### ISSUE THREAD

**Issue by daserra23** [derenback/Domoticz-SMA-Inverter#28]
I tried to install the pyModbus and pyModbusTCP modules on Debian12 but it wouldn't let me due to this new virtual python enviroment breaking change. So I then tried adding "--break-system-packages" to the end of the pip3 installation command but this installed the modules in a location this plugin couldn't find. I then finally found a command to install these modules where the plugin expects them.

`sudo python3.12 -m pip install --target=/usr/lib/python3/dist-packages --break-system-packages pymodbus

sudo python3.12 -m pip install --target=/usr/lib/python3.12/dist-packages --break-system-packages pymodbus

sudo python3.12 -m pip install --target=/usr/lib/python3/dist-packages --break-system-packages pymodbusTCP

sudo python3.12 -m pip install --target=/usr/lib/python3.12/dist-packages --break-system-packages pymodbusTCP`

Once I did this the plugin worked properly so I just I'd put this here in case anyone else finds it useful. This was on Ubuntu server, no docker, Domoticz 2024.7

**Comment by derenback** [comment]
My recommendation is to use docker or similar to run Domoticz instead of installing hings native on the host. 
Will close this issue and your instruction will still be visible in the closed issue.

**Comment by daserra23** [comment]
It was actually this plugin that required the modules in the "right" place. I've tried unsuccessfully twice , both times over a few days, to install Domoticz in the docker so I now run it in a VM.

**Comment by derenback** [comment]
Have you tried it with my Docker instructions here: https://github.com/derenback/Domoticz-SMA-Inverter-Docker
I have a docker file and a docker compose example file.
Have tested it on Ubuntu and it works fine for me.
I currently run docker o two Raspberry pi and a computer with Ubuntu 24.04

Domoticz pluginsystem is a bit tricky when you need to install things on the host.
