### ISSUE TITLE
Enhancement: Do not run at night

### ISSUE THREAD

**Issue by daserra23** [derenback/Domoticz-SMA-Inverter#29]
I've recently added full logging and I've noticed that the plugin runs at night according to the interval, perhaps it would be better if it only runs during daylight hours as SMA Inverters shut down at night and don't respond.

**Comment by derenback** [comment]
I have thought about this before but not done it due to the issue with sensor timeout. All sensors not updated for that time will become "red", indicating a warning...

**Comment by daserra23** [comment]
Maybe a once an hour placeholder update or another reduced frequency based upon sunset and sunset times in Domoticz ? Admittedly difficult to resolve the 2 things.

**Comment by derenback** [comment]
Have tried to figure out how to read the sensor timeout setting from Domoticz but have not figured it out... will take a look at this after Christmas.

**Comment by daserra23** [comment]
Brilliant. I was messing around with some of the AI's that helped me create this snippet that could be useful.

https://github.com/daserra23/Location-aware-night-polling-inhibitor/blob/main/script-snippet.py

However, enjoy Christmas *clink*
