### ISSUE TITLE
Purpose

### ISSUE THREAD

**Issue by flopp999** [derenback/Domoticz-SMA-Inverter#7]
What is the purpose of having two almost identical devices?
![image](https://user-images.githubusercontent.com/21694965/158610226-b8c2437c-b051-422e-a31d-d4776ae734c9.png)
Solar Production is showing today as primary and total as secondary.
AC Power is showing instantaneous as primary and today as secondary.

Log for AC Power is showing total så maybe one of the devices can be deleted?

**Comment by derenback** [comment]
AC power shows the power and the produced kWh for this day.
Solar production also show the Total kWhs since the start. Sort of the same as your power meeter for your consumption.

**Comment by derenback** [comment]
Where do you see total kWh in the AC power log?

**Comment by flopp999** [comment]
Log-Report(up right) there you will see more data
![image](https://user-images.githubusercontent.com/21694965/158631063-bebc0904-9dd8-459f-96d1-d27ea296a2f7.png)

**Comment by derenback** [comment]
Ok, yes... I did not know that. But it is not possible to present the total in an easy way on my control panel.
Removing this sensor would not decrease the number of requests to the inverter since the data is still used for AC power. 
It would decrease the amoit of data in the domoticz database but it would also be a "breaking change" if somone use this information for something else. Lets think about it. Not sure I agree to remove it.

**Comment by flopp999** [comment]
Device = ID Numbers for my SMA VR(STP 10.0)

AC power: consumption right now and production right now, you get a minus(-) in front of production
Today = how much Energy I have bought, value after this is counter for bought electricity 
Return = Today how much energy I have produced, value after this is counter for production.

Sold is showing how much you have put to the Grid


I will upload a PR today or next weekend

![image](https://user-images.githubusercontent.com/21694965/159007827-f1458b38-5dfd-4dd0-959b-2949faa127ad.png)

**Comment by derenback** [comment]
I guess this require a smart meeter that can tell the difference in production and self consumtion? Only the Inverter will not give this value? Please ad a PR and I can see how you got this to work.

**Comment by flopp999** [comment]
I have always have a Smart Meter so I am not sure. But I think you only get Yield(produced) if you dont have a smart meter.
I will try to get information from Inverter if a Smart Meter exist and then make the code to create device depends on that information

**Comment by flopp999** [comment]
@derenback 
if you are a member of domotica forum could you please send me a message
https://www.domoticz.com/forum/memberlist.php?mode=viewprofile&u=8270

**Comment by derenback** [comment]
@flopp999 Sorry... but not a member.

**Comment by flopp999** [comment]
Can I have your email.
We can do some test together and it is easier with email or WhatsApp etc

**Comment by flopp999** [comment]
my twitter @DanielN66323117

**Comment by flopp999** [comment]
FB https://www.facebook.com/profile.php?id=501936518
